services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - 30306:3306

  adminer:
    image: adminer
    ports:
      - 8888:8080

volumes:
  data: